### ISSUE TITLE
SVGs are getting passed to lqip

### ISSUE THREAD

**Issue by wbobeirne** [cyrilwanner/next-optimized-images#121]
After adding `next-optimized-images` to my existing project, I got the following error:

```
Error: Input file is missing or of an unsupported image format lqip v2.1.0
/Users/will/Documents/project/node_modules/lqip/index.js:76
  throw up;
  ^

ReferenceError: err is not defined
    at Promise.all.then.catch.error (/Users/will/Documents/project/node_modules/lqip-loader/index.js:80:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I edited the `lqip` module to give more information, and found that it is getting passed an `svg`. My short term fix was to remove `svg` from the `handleImages` array, but ideally this loader should only include files that `lqip` supports.

**Comment by stevenmunro** [comment]
I'm also having trouble with this. As I use ?lqip in a custom component I build for handling images, if I have a SVG on the page the build fails. Unless of course I have a custom handler for .svg files in next.config.js. This defeats the purpose of this module if I want to also use ?sprite.

Any particular reason why svg files are being passed through lqip-loader?
