### ISSUE TITLE
Canary breaks build

### ISSUE THREAD

**Issue by fandy** [cyrilwanner/next-optimized-images#164]
`^3.0.0-canary.0` makes it so that Next.js can't build with `next build`. Note that it **runs in development fine**.

Build logs:
```
yarn install v1.22.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@apollo/react-hooks > @apollo/react-common@3.1.4" has unmet peer dependency "apollo-utilities@^1.3.2".
warning " > material-table@1.57.2" has unmet peer dependency "@date-io/core@^1.3.6".
warning "material-table > @material-ui/pickers@3.2.10" has unmet peer dependency "@date-io/core@^1.3.6".
warning "react-apollo > @apollo/react-components@3.1.5" has unmet peer dependency "apollo-cache@^1.3.2".
warning "react-apollo > @apollo/react-components@3.1.5" has unmet peer dependency "apollo-link@^1.2.12".
warning "react-apollo > @apollo/react-components@3.1.5" has unmet peer dependency "apollo-utilities@^1.3.2".
warning " > styled-components@5.1.0" has unmet peer dependency "react-is@>= 16.8.0".
warning " > babel-loader@8.1.0" has unmet peer dependency "webpack@>=2".
warning " > file-loader@6.0.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > url-loader@4.1.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "react-docgen-typescript-loader > @webpack-contrib/schema-utils@1.0.0-beta.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
[5/5] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error /app/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /app/node_modules/sharp
Output:
ERR! sharp 'darwin-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linux-x64' platform.
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.16.1 | linux | x64
gyp info find Python using Python version 2.7.13 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v12.16.1/node-v12.16.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v12.16.1/node-v12.16.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v12.16.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v12.16.1/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/app/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/12.16.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/12.16.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/12.16.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/app/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/app/node_modules/sharp/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  AR(target) Release/obj.target/../node-addon-api/nothing.a
  COPY Release/nothing.a
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  SOLINK_MODULE(target) Release/obj.target/sharp.node
g++: error: ../vendor/lib/libvips-cpp.so: No such file or directory
g++: error: ../vendor/lib/libvips.so: No such file or directory
g++: error: ../vendor/lib/libglib-2.0.so: No such file or directory
g++: error: ../vendor/lib/libgobject-2.0.so: No such file or directory
g++: error: ../vendor/lib/libcairo.so: No such file or directory
g++: error: ../vendor/lib/libexif.so: No such file or directory
g++: error: ../vendor/lib/libexpat.so: No such file or directory
g++: error: ../vendor/lib/libffi.so: No such file or directory
g++: error: ../vendor/lib/libfontconfig.so: No such file or directory
g++: error: ../vendor/lib/libfreetype.so: No such file or directory
g++: error: ../vendor/lib/libfribidi.so: No such file or directory
g++: error: ../vendor/lib/libgdk_pixbuf-2.0.so: No such file or directory
g++: error: ../vendor/lib/libgif.so: No such file or directory
g++: error: ../vendor/lib/libgio-2.0.so: No such file or directory
g++: error: ../vendor/lib/libgmodule-2.0.so: No such file or directory
g++: error: ../vendor/lib/libgsf-1.so: No such file or directory
g++: error: ../vendor/lib/libgthread-2.0.so: No such file or directory
g++: error: ../vendor/lib/libharfbuzz.so: No such file or directory
g++: error: ../vendor/lib/libjpeg.so: No such file or directory
g++: error: ../vendor/lib/liblcms2.so: No such file or directory
g++: error: ../vendor/lib/liborc-0.4.so: No such file or directory
g++: error: ../vendor/lib/libpango-1.0.so: No such file or directory
g++: error: ../vendor/lib/libpangocairo-1.0.so: No such file or directory
g++: error: ../vendor/lib/libpangoft2-1.0.so: No such file or directory
g++: error: ../vendor/lib/libpixman-1.so: No such file or directory
g++: error: ../vendor/lib/libpng.so: No such file or directory
g++: error: ../vendor/lib/librsvg-2.so: No such file or directory
g++: error: ../vendor/lib/libtiff.so: No such file or directory
g++: error: ../vendor/lib/libwebp.so: No such file or directory
g++: error: ../vendor/lib/libwebpdemux.so: No such file or directory
g++: error: ../vendor/lib/libwebpmux.so: No such file or directory
g++: error: ../vendor/lib/libxml2.so: No such file or directory
g++: error: ../vendor/lib/libz.so: No such file or directory
sharp.target.mk:201: recipe for target 'Release/obj.target/sharp.node' failed
make: Leaving directory '/app/node_modules/sharp/build'
make: *** [Release/obj.target/sharp.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.76-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/sharp
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
ERROR: Service 'nextjs' failed to build: The command '/bin/sh -c yarn' returned a non-zero code: 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by cyrilwanner** [comment]
Thank you for testing out the canary version!
Does the build run on exactly the same machine & environment or somewhere else?

It looks like this could be an issue with sharp: `ERR! sharp 'darwin-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linux-x64' platform.`
Did you try to re-install sharp? Or if that does not work, re-install all node_modules?
