### ISSUE TITLE
[canary] broken production build for static pages inside Docker

### ISSUE THREAD

**Issue by arusakov** [cyrilwanner/next-optimized-images#196]
When I try build the project in Ubuntu 18.04 it's okay. There are only warnings about MaxListeners.
But inside the Docker build is failed.

**Related packages versions**
- "next": "9.5.2"
- "next-optimized-images": "3.0.0-canary.10"

**Tested docker versions**:
- node:12.18.03
- node:12.18.03-alpine

`next build` output from `docker build`:
```
info  - Creating an optimized production build...
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

(node:28) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:28) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added to [process]. Use emitter.setMaxListeners() to increase limit
info  - Compiled successfully
info  - Collecting page data...
info  - Generating static pages (0/4)

Error occurred prerendering page "/empty". Read more: https://err.sh/next.js/prerender-error
Error: Babel plugin 'react-optimized-image/plugin' not installed or this component could not be recognized by it.
    at Img (/cc-web/node_modules/react-optimized-image/lib/components/Img.js:119:11)
    at d (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
    at $a (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at Object.renderPage (/cc-web/node_modules/next/dist/next-server/server/render.js:48:686)
    at Function.getInitialProps (/cc-web/.next/server/pages/_document.js:364:19)
    at loadGetInitialProps (/cc-web/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/cc-web/node_modules/next/dist/next-server/server/render.js:48:977)

Error occurred prerendering page "/sitemap". Read more: https://err.sh/next.js/prerender-error
Error: Babel plugin 'react-optimized-image/plugin' not installed or this component could not be recognized by it.
    at Img (/cc-web/node_modules/react-optimized-image/lib/components/Img.js:119:11)
    at d (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
    at $a (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at Object.renderPage (/cc-web/node_modules/next/dist/next-server/server/render.js:48:686)
    at Function.getInitialProps (/cc-web/.next/server/pages/_document.js:364:19)
    at loadGetInitialProps (/cc-web/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/cc-web/node_modules/next/dist/next-server/server/render.js:48:977)
info  - Generating static pages (1/4)
info  - Generating static pages (2/4)

Error occurred prerendering page "/404". Read more: https://err.sh/next.js/prerender-error
Error: Babel plugin 'react-optimized-image/plugin' not installed or this component could not be recognized by it.
    at Img (/cc-web/node_modules/react-optimized-image/lib/components/Img.js:119:11)
    at d (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
    at $a (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at Object.renderPage (/cc-web/node_modules/next/dist/next-server/server/render.js:48:686)
    at Function.getInitialProps (/cc-web/.next/server/pages/_document.js:364:19)
    at loadGetInitialProps (/cc-web/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/cc-web/node_modules/next/dist/next-server/server/render.js:48:977)
info  - Generating static pages (3/4)

Error occurred prerendering page "/about". Read more: https://err.sh/next.js/prerender-error
Error: Babel plugin 'react-optimized-image/plugin' not installed or this component could not be recognized by it.
    at Img (/cc-web/node_modules/react-optimized-image/lib/components/Img.js:119:11)
    at d (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
    at $a (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at Object.renderPage (/cc-web/node_modules/next/dist/next-server/server/render.js:48:686)
    at Function.getInitialProps (/cc-web/.next/server/pages/_document.js:364:19)
    at loadGetInitialProps (/cc-web/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/cc-web/node_modules/next/dist/next-server/server/render.js:48:977)
info  - Generating static pages (4/4)

> Build error occurred
Error: Export encountered errors on following paths:
        /404
        /about
        /empty
        /sitemap
    at exportApp (/cc-web/node_modules/next/dist/export/index.js:24:1103)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async build (/cc-web/node_modules/next/dist/build/index.js:37:212)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn build' returned a non-zero code: 1
```

**Comment by semyou** [comment]
Got the same error when I compile on my production server
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:28) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added to [process]. Use emitter.setMaxListeners() to increase limit
and then I see the process eating up all my servers memory before it crushes.

**Comment by naavis** [comment]
I'm bumping into this same issue on my workstation without Docker with the following output:
```
> next build

info  - Using external babel configuration from [censored]\.babelrc
(node:5108) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:5108) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added to [process]. Use emitter.setMaxListeners() to increase limit
RangeError: WebAssembly.Memory(): could not allocate memory
RangeError: WebAssembly.Memory(): could not allocate memory
info  - Creating an optimized production build .[censored]\node_modules\@wasm-codecs\mozjpeg\lib\mozjpeg.js:9
var Module=typeof mozjpeg!=="undefined"?mozjpeg:{};var readyPromiseResolve,readyPromiseReject;Module["ready"]=new Promise(function(resolve,reject){readyPromiseResolve=resolve;readyPromiseReject=reject});var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){

RuntimeError: abort(RangeError: WebAssembly.Memory(): could not allocate memory). Build with -s ASSERTIONS=1 for more info.
    at process.abort ([censored]\node_modules\@wasm-codecs\mozjpeg\lib\mozjpeg.js:9:11556)
    at process.emit (events.js:323:22)
    at processEmit [as emit] ([censored]\node_modules\next\dist\compiled\ora\index.js:1:2260)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! next-homepage@0.1.0 build: `next build`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the next-homepage@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     [censored]\AppData\Roaming\npm-cache\_logs\2020-09-13T11_52_00_853Z-debug.log
```

I am on Next.js 9.5.3, next-optimized-images 3.0.0-canary.10 and Node 12.16.1.

**Comment by semyou** [comment]
@naavis try to delete .next and node_modules and do an npm install again and see if it solves your problem. It did for me. However, my problem is the memory hog that this plugin is. My npm build always fails on my 2G RAM VPS with just 4 images. Works fine on my laptop though. :(

**Comment by naavis** [comment]
@semyou That unfortunately did not fix the problem. I am resizing about 200 pictures during the build. The originals only total 128 megabytes, though, and I'm running with 16GB of RAM.

**Comment by nicotsx** [comment]
Any news about this one ? I cannot build on vercel anymore. Working fine on local machine

**Comment by bh** [comment]
> I'm bumping into this same issue on my workstation without Docker with the following output:
> 
> ```
> > next build
> 
> info  - Using external babel configuration from [censored]\.babelrc
> (node:5108) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
> (node:5108) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added to [process]. Use emitter.setMaxListeners() to increase limit
> RangeError: WebAssembly.Memory(): could not allocate memory
> RangeError: WebAssembly.Memory(): could not allocate memory
> info  - Creating an optimized production build .[censored]\node_modules\@wasm-codecs\mozjpeg\lib\mozjpeg.js:9
> var Module=typeof mozjpeg!=="undefined"?mozjpeg:{};var readyPromiseResolve,readyPromiseReject;Module["ready"]=new Promise(function(resolve,reject){readyPromiseResolve=resolve;readyPromiseReject=reject});var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){
> 
> RuntimeError: abort(RangeError: WebAssembly.Memory(): could not allocate memory). Build with -s ASSERTIONS=1 for more info.
>     at process.abort ([censored]\node_modules\@wasm-codecs\mozjpeg\lib\mozjpeg.js:9:11556)
>     at process.emit (events.js:323:22)
>     at processEmit [as emit] ([censored]\node_modules\next\dist\compiled\ora\index.js:1:2260)
>     at processPromiseRejections (internal/process/promises.js:209:33)
>     at processTicksAndRejections (internal/process/task_queues.js:98:32)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 7
> npm ERR! next-homepage@0.1.0 build: `next build`
> npm ERR! Exit status 7
> npm ERR!
> npm ERR! Failed at the next-homepage@0.1.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     [censored]\AppData\Roaming\npm-cache\_logs\2020-09-13T11_52_00_853Z-debug.log
> ```
> 
> I am on Next.js 9.5.3, next-optimized-images 3.0.0-canary.10 and Node 12.16.1.

Try this: https://github.com/cyrilwanner/next-optimized-images/issues/186#issuecomment-753632391

**Comment by bh** [comment]
> When I try build the project in Ubuntu 18.04 it's okay. There are only warnings about MaxListeners.
> But inside the Docker build is failed.
> 
> **Related packages versions**
> 
>     * "next": "9.5.2"
> 
>     * "next-optimized-images": "3.0.0-canary.10"
> 
> 
> **Tested docker versions**:
> 
>     * node:12.18.03
> 
>     * node:12.18.03-alpine
> 
> 
> `next build` output from `docker build`:
> 
> ```
> info  - Creating an optimized production build...
> Attention: Next.js now collects completely anonymous telemetry regarding usage.
> This information is used to shape Next.js' roadmap and prioritize features.
> You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
> https://nextjs.org/telemetry
> 
> (node:28) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
> (node:28) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added to [process]. Use emitter.setMaxListeners() to increase limit
> info  - Compiled successfully
> info  - Collecting page data...
> info  - Generating static pages (0/4)
> 
> Error occurred prerendering page "/empty". Read more: https://err.sh/next.js/prerender-error
> Error: Babel plugin 'react-optimized-image/plugin' not installed or this component could not be recognized by it.
>     at Img (/cc-web/node_modules/react-optimized-image/lib/components/Img.js:119:11)
>     at d (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
>     at $a (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
>     at a.b.render (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
>     at a.b.read (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
>     at renderToString (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
>     at Object.renderPage (/cc-web/node_modules/next/dist/next-server/server/render.js:48:686)
>     at Function.getInitialProps (/cc-web/.next/server/pages/_document.js:364:19)
>     at loadGetInitialProps (/cc-web/node_modules/next/dist/next-server/lib/utils.js:5:101)
>     at renderToHTML (/cc-web/node_modules/next/dist/next-server/server/render.js:48:977)
> 
> Error occurred prerendering page "/sitemap". Read more: https://err.sh/next.js/prerender-error
> Error: Babel plugin 'react-optimized-image/plugin' not installed or this component could not be recognized by it.
>     at Img (/cc-web/node_modules/react-optimized-image/lib/components/Img.js:119:11)
>     at d (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
>     at $a (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
>     at a.b.render (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
>     at a.b.read (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
>     at renderToString (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
>     at Object.renderPage (/cc-web/node_modules/next/dist/next-server/server/render.js:48:686)
>     at Function.getInitialProps (/cc-web/.next/server/pages/_document.js:364:19)
>     at loadGetInitialProps (/cc-web/node_modules/next/dist/next-server/lib/utils.js:5:101)
>     at renderToHTML (/cc-web/node_modules/next/dist/next-server/server/render.js:48:977)
> info  - Generating static pages (1/4)
> info  - Generating static pages (2/4)
> 
> Error occurred prerendering page "/404". Read more: https://err.sh/next.js/prerender-error
> Error: Babel plugin 'react-optimized-image/plugin' not installed or this component could not be recognized by it.
>     at Img (/cc-web/node_modules/react-optimized-image/lib/components/Img.js:119:11)
>     at d (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
>     at $a (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
>     at a.b.render (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
>     at a.b.read (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
>     at renderToString (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
>     at Object.renderPage (/cc-web/node_modules/next/dist/next-server/server/render.js:48:686)
>     at Function.getInitialProps (/cc-web/.next/server/pages/_document.js:364:19)
>     at loadGetInitialProps (/cc-web/node_modules/next/dist/next-server/lib/utils.js:5:101)
>     at renderToHTML (/cc-web/node_modules/next/dist/next-server/server/render.js:48:977)
> info  - Generating static pages (3/4)
> 
> Error occurred prerendering page "/about". Read more: https://err.sh/next.js/prerender-error
> Error: Babel plugin 'react-optimized-image/plugin' not installed or this component could not be recognized by it.
>     at Img (/cc-web/node_modules/react-optimized-image/lib/components/Img.js:119:11)
>     at d (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
>     at $a (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
>     at a.b.render (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
>     at a.b.read (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
>     at renderToString (/cc-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
>     at Object.renderPage (/cc-web/node_modules/next/dist/next-server/server/render.js:48:686)
>     at Function.getInitialProps (/cc-web/.next/server/pages/_document.js:364:19)
>     at loadGetInitialProps (/cc-web/node_modules/next/dist/next-server/lib/utils.js:5:101)
>     at renderToHTML (/cc-web/node_modules/next/dist/next-server/server/render.js:48:977)
> info  - Generating static pages (4/4)
> 
> > Build error occurred
> Error: Export encountered errors on following paths:
>         /404
>         /about
>         /empty
>         /sitemap
>     at exportApp (/cc-web/node_modules/next/dist/export/index.js:24:1103)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async build (/cc-web/node_modules/next/dist/build/index.js:37:212)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> The command '/bin/sh -c yarn build' returned a non-zero code: 1
> ```

Try this: https://github.com/cyrilwanner/next-optimized-images/issues/186#issuecomment-753632391
