### ISSUE TITLE
Error on require image

### ISSUE THREAD

**Issue by stephane-r** [cyrilwanner/next-optimized-images#36]
Hi :)

After install your module, i try to require an png image : 

`const src = require('./glouman-company-homepage.png');`

But i've an error : 

```
 error  in ./src/client/components/HomeBanner/glouman-company-homepage.png

Module build failed (from /home/project-name/node_modules/url-loader/index.js):
TypeError: Cannot read property 'context' of undefined
    at Object.loader (/home/project-name/node_modules/file-loader/dist/index.js:34:49)
    at Object.module.exports (/home/project-name/node_modules/url-loader/index.js:37:25)
```

I've been create `next.config.js` file on same path level `pages`.

I use latest next@7.1. Anyone have idea ?

**Comment by cyrilwanner** [comment]
Hi @stephane-r 	

Can you maybe post your `next.config.js` file if nothing sensitive is in it? When an error occurs within your image (error in .. .png), it is mostly just a configuration issue and another plugin is interfering and tries to also do something with that image.

**Comment by donald-stolz** [comment]
Hi @cyrilwanner 

I am currently getting the same error. Here is my current `next.config.js`

``` js
// next.config.js
require('dotenv').config();
const prod = process.env.NODE_ENV === 'production';
const path = require('path');
const Dotenv = require('dotenv-webpack');
const typeScript = require('@zeit/next-typescript');
const optimizedImages = require('next-optimized-images');
const withPlugins = require('next-compose-plugins');

const nextConfig = {
  webpack: config => {
    config.plugins = config.plugins || [];

    config.plugins = [
      ...config.plugins,

      // Read the .env file
      new Dotenv({
        path: prod
          ? path.join(__dirname, '.env.production')
          : path.join(__dirname, '.env.dev'),
        systemvars: true,
      }),
    ];

    return config;
  },
  onDemandEntries: {
    // This governs the behavior of the development server ONLY
    // period (in ms) where the server will keep pages in the buffer
    maxInactiveAge: 5 * 60 * 1000,
    // number of pages that should be kept simultaneously without being disposed
    pagesBufferLength: 10,
  },
};

module.exports = withPlugins(
  [
    [
      optimizedImages,
      {
        /* config for next-optimized-images */
        optimizeImagesInDev: true,
      },
    ],
    [typeScript],
  ],
  nextConfig,
);
```
