### ISSUE TITLE
Deployment error with now 2.0

### ISSUE THREAD

**Issue by r0b-** [cyrilwanner/next-optimized-images#58]
Hi,

I'm getting the following error for all my images when running the `now` command (dev mode and prod builds are fine).  
In my TypeScript code I include the images via `require("../static/icons/logo.svg?include")` or similar. 

```
ModuleNotFoundError: Module not found: Error: Can't resolve '../static/icons/logo.svg?include' in '/tmp/48d87981/components'
    at factory.create (/tmp/48d87981/node_modules/webpack/lib/Compilation.js:821:10)
    at factory (/tmp/48d87981/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/tmp/48d87981/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/tmp/48d87981/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /tmp/48d87981/node_modules/neo-async/async.js:2825:7
    at /tmp/48d87981/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/tmp/48d87981/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/tmp/48d87981/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/tmp/48d87981/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/tmp/48d87981/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/tmp/48d87981/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/tmp/48d87981/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/tmp/48d87981/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/tmp/48d87981/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/tmp/48d87981/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/tmp/48d87981/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
resolve '../static/icons/logo.svg?include' in '/tmp/48d87981/components'
  using description file: /tmp/48d87981/package.json (relative path: ./components)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /tmp/48d87981/package.json (relative path: ./static/icons/logo.svg)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /tmp/48d87981/static/icons/logo.svg doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /tmp/48d87981/static/icons/logo.svg.wasm doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        /tmp/48d87981/static/icons/logo.svg.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /tmp/48d87981/static/icons/logo.svg.js doesn't exist
      .jsx
        Field 'browser' doesn't contain a valid alias configuration
        /tmp/48d87981/static/icons/logo.svg.jsx doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /tmp/48d87981/static/icons/logo.svg.json doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /tmp/48d87981/static/icons/logo.svg.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        /tmp/48d87981/static/icons/logo.svg.tsx doesn't exist
      as directory
        /tmp/48d87981/static/icons/logo.svg doesn't exist
```

(next 8 canary, next-optimized-images 2.3.3, now 2.0)

Thanks in advance

**Comment by r0b-** [comment]
see https://github.com/zeit/next.js/issues/6090
