### ISSUE TITLE
svg?sprite Cannot find module svg-baker-runtime/symbol.js

### ISSUE THREAD

**Issue by Purii** [cyrilwanner/next-optimized-images#75]
Thanks for your awesome library!

Unfortunately I'm unable to get svg sprites working.
After starting up the dev server it throws the following error:

```bash
Error: Cannot find module './node_modules/svg-baker-runtime/symbol.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
```

I set it up as written in the README.md on a new next.js project (using `yarn create next-app`).
Also tried to add `svg-baker-runtime` additionally in case there's a new version with a fix.

Any ideas?

**Comment by Emiliano-Bucci** [comment]
Hello! I have the same error after updating to last version; any clues? Thanks!

**Comment by cyrilwanner** [comment]
It looks like this bug was introduced by version `4.1.4` of `svg-sprite-loader` which was released a few days ago.
You can go back to `4.1.3` with `npm install svg-sprite-loader@4.1.3` until I figure out if next-optimized-images does something wrong or if it is indeed a bug in the sprite loader.

**Comment by papirovnyk** [comment]
Had the same issue, try downgrade version to **npm install svg-sprite-loader@4.1.2**

**Comment by Emiliano-Bucci** [comment]
@cyrilwanner Is there any update on this issue? Still having issues with the `4.1.6v` :/

**Comment by mikevercoelen** [comment]
Same problem here

**Comment by kvlsrg** [comment]
Related to: https://github.com/JetBrains/svg-sprite-loader/issues/186

**Comment by semirart** [comment]
The issue is fixed in svg-sprite-loader@5.0.0.
